#!/bin/bash

source get_params <<< "$@"


do_exit=false
if [ "$secret" = "" ]; then
  echo "❌  No --secret specified."
  do_exit=true
fi

if [ $do_exit = "true" ]; then
  echo "👋 Exiting"
  exit 1
fi

if [ $namespace = "" ]; then
  kubectl get secret "$secret" -o json | jq '.data | map_values(@base64d)'
else
  kubectl get secret "$secret" -n $namespace -o json | jq '.data | map_values(@base64d)'
fi
