#!/bin/bash

source get_params <<< "$@"


do_exit=false
if [ "$secret" = "" ]; then
  echo "❌  No --secret specified."
  do_exit=true
fi

if [ $do_exit = "true" ]; then
  echo "👋 Exiting"
  exit 1
fi

kubectl get secret "$secret" -o json | jq '.data | map_values(@base64d)'
