#!/usr/bin/env bash

set -e

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

# Parameters
contexts=
replicas=1
services=
source "$SCRIPT_DIR/get_params" <<< $@

do_exit=false
if [ "$contexts" = "" ]; then
  echo "❌  No --contexts specified."
  do_exit=true
fi

if [ "$services" = "" ]; then
  echo "❌  No --services specified."
  do_exit=true
fi

if [ $do_exit = "true" ]; then
  echo "👋 Exiting"
  exit 1
fi
for context in ${contexts//,/ }
do
  for service in ${services//,/ }
  do
    kubectl --context $context scale deployment $service --replicas $replicas
  done
done
